### ISSUE TITLE
requirements.txt is out of date

### ISSUE THREAD

**Issue by StephenHnilica** [EnigmAI/Artistia#23]
Attempting to install the requirements, I get the error that mkl-random 1.1.1 cannot be found.

Attempting to change the requirements to mkl-random==1.2.1 leads to issues with tensorflow-gpu-estimator for which I cannot find a remedy for.

**Comment by StephenHnilica** [comment]
There are a few packages that are no longer available, making this not able to be installed.

I know mkl-random is one of them. I'm also having issues with

**Comment by StephenHnilica** [comment]
Not sure why this was closed. New to interacting on GitHub.

**Comment by Frostday** [comment]
requirements.txt has been fixed now. Make a pull request to update your forked branch and then try it out.
In case you face another issue then try installing all packages in the req.txt file instead.
